### PR TITLE
breaking: Textures: change the type of NewTextureFromRgba

### LINKED ISSUE #316: Texture loading: app hangs on when loading texture in main thread
It may be related with #111 ?...
when calling `NewTextureFromRgba` in main thread (e.g. in giu.Custom) the app stops rendering and gots stuck
here is a demo code:
```golang
package main

import (
	"fmt"
	"image"

	"github.com/AllenDang/giu"
)

func loop() {
	giu.SingleWindow().Layout(
		giu.Custom(func() {
			fmt.Println("ping")
			rgba := image.NewRGBA(image.Rect(0, 0, 10, 10))
			giu.NewTextureFromRgba(rgba)
			fmt.Println("pong")
		}),
	)
}

func main() {
	wnd := giu.NewMasterWindow("App crash on loading textures [Demo]", 640, 480, 0)
	wnd.Run(loop)
}
```

### PR DESCRIPTION
**Pull request by gucio321**
because of the issues with loading textures in mainthread it is better to allow the giu to call a callback when it is done with loading the texture.
change type of NewTextureFromRgba: func(imag.Image) (*Texture, error) -> func(image.Image, func(*Texture)).
this should fix #316

### CODE REVIEW

File: Texture.go [hunk 1]
```diff
@@ -19,25 +19,31 @@ type loadImageResult struct {
...
+			return &loadImageResult{id: texId, err: err}
+		})
+
+		tid, ok := result.(*loadImageResult)
+		switch {
+		case !ok:
+			panic("giu: NewTextureFromRgba: unexpected error occured")
+		case tid.err != nil:
+			panic(fmt.Sprintf("giu: NewTextureFromRgba: error loading texture: %v", tid.err))
+		}
```
Comment (gucio321) [inline Texture.go:37]: @AllenDang is there any commonly known (expected) case when this may happen?
I mean if calling panic is ok here or should I handle it in any other way?

Comment (AllenDang) [reply Texture.go:37]: @gucio321 I think panic is ok for now.
